

#ifndef PJC_PROJECT_STATES_H
#define PJC_PROJECT_STATES_H


enum States {
    IS_FIRST_SPLASH_ACTIVE,
    FOCUSED_INPUT_TEXT,
    FOCUSED_INPUT_ID,
    IS_PICKING_UP_DOUBLE_JUMP_ABILITY,
};

#endif //PJC_PROJECT_STATES_H
